name: Update Docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies (docs group)
        run: uv sync --group docs

      - name: Build Documentation
        run: uv run mkdocs build

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./site
          user_name: GitHub Actions
          user_email: actions@github.com
          publish_branch: gh-pages